services:
  app:
    build: .
    container_name: med-records-api
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5438/postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    command: [ "python", "src/main.py" ]

  db:
    image: postgres:15
    container_name: med-records-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
