"""init

Revision ID: c2c6f795a3e0
Revises: 
Create Date: 2025-05-18 20:38:48.450492

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c2c6f795a3e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=False),
                    sa.Column('specialization', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('patients',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=False),
                    sa.Column('birth_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('visits',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('patient_id', sa.UUID(), nullable=False),
                    sa.Column('doctor_id', sa.UUID(), nullable=False),
                    sa.Column('visit_date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
                    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('attachments',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('visit_id', sa.UUID(), nullable=False),
                    sa.Column('file_path', sa.String(), nullable=False),
                    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('diagnoses',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('visit_id', sa.UUID(), nullable=False),
                    sa.Column('code', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('prescriptions',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('visit_id', sa.UUID(), nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescriptions')
    op.drop_table('diagnoses')
    op.drop_table('attachments')
    op.drop_table('visits')
    op.drop_table('patients')
    op.drop_table('doctors')
    # ### end Alembic commands ###
